## Algorithm:

- Take dataset and split into dependent and independent.

- Initialize weights and bias to 0.

- For each epoch, find ypred, dw, db and update weight and bias.

- Continue running epochs, until loss function becomes stagnant.

- Predict values of test set and evaluate.

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

## Dataset

In [2]:
X, y = datasets.make_regression(n_samples=100, n_features=2, noise=20, random_state=10)

In [3]:
X.shape, y.shape

((100, 2), (100,))

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [5]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((80, 2), (20, 2), (80,), (20,))

In [6]:
X_train[:5]

array([[-1.97772828, -1.7433723 ],
       [ 0.94250041, -2.97959677],
       [-0.28762941, -1.35931057],
       [-0.70707145,  0.54666484],
       [-0.33914025,  0.31216994]])

In [7]:
y_train[:5]

array([-252.81242619,  -74.27309965, -100.72618959,  -55.69834737,
         -5.54285386])

## Model building

In [8]:
class LinearRegression:
    def __init__(self, learn_rate, num_iters):
        self.weights = None
        self.bias = None
        self.learn_rate = learn_rate
        self.num_iters = num_iters
    
    def fit(self, X, y):                                          # for training the model
        samples, features = X.shape
        self.weights = np.zeros(features)                         # initialising weights as 0 for all features
        self.bias = 0                                             # initialising with bias as 0

        for epoch in range(self.num_iters):
            y_pred = np.dot(X, self.weights) + self.bias          # ypred = b + wX
            loss = ((y_pred-y)**2).mean()                         # MSE: Loss = 1/N * ((w*X+b) - y)**2
            dw = (1 / samples) * 2 * np.dot(X.T, (y_pred - y))    # dLoss/dw = 1/N * 2X(w*X+b - y)
            db = (1 / samples) * 2 * np.sum(y_pred - y)           # dLoss/db = 1/N * 2(w*X+b - y)
            self.weights = self.weights - (self.learn_rate*dw)    # update weight
            self.bias = self.bias - (self.learn_rate*db)          # update bias

            if (epoch%30==0):                                     # just to print loss and weights after some epochs
              print(f'epoch {epoch+1}: weights = [{self.weights[0]:.4f}, {self.weights[1]:.4f}], loss = {loss:.4f}')

    def predict(self, X):                                         # for prediction
        y_pred = np.dot(X, self.weights) + self.bias
        return y_pred

**Logic behind dot products**

np.dot(X, self.weights) --> (80,2) * (2,) = (80,)

for every sample we get 2 value (the 2 is because we have 2 features)

and in the transposed case,

np.dot(X.T, (y_predicted - y)) --> (2, 80) * (80,) = (2,)

for every feature we get 2 values

In [9]:
model = LinearRegression(learn_rate=0.01, num_iters=300)
model.fit(X_train, y_train)                                       # used to train model and update w, b
y_pred = model.predict(X_test)

epoch 1: weights = [1.4859, 1.3780], loss = 10044.6078
epoch 31: weights = [35.0238, 30.1344], loss = 3067.7479
epoch 61: weights = [54.0888, 43.5090], loss = 1136.5925
epoch 91: weights = [65.1520, 49.4784], loss = 576.6096
epoch 121: weights = [71.7090, 51.9566], loss = 403.2974
epoch 151: weights = [75.6773, 52.8418], loss = 345.1643
epoch 181: weights = [78.1267, 53.0390], loss = 323.9311
epoch 211: weights = [79.6660, 52.9680], loss = 315.5575
epoch 241: weights = [80.6489, 52.8159], loss = 312.0525
epoch 271: weights = [81.2849, 52.6598], loss = 310.5238


In [10]:
y_pred[:5]

array([ 172.38612066,  148.3156678 ,   57.51809851,   67.26374421,
       -161.36987961])

In [11]:
y_test[:5]

array([ 164.1826212 ,  130.46580874,   62.77042267,   85.39016543,
       -200.94244523])

## Evaluating test data

In [12]:
def loss(Yhat, Y):
  return ((y_pred-y_test)**2).mean()

def r2_score(y_test, y_pred):
    corr_matrix = np.corrcoef(y_test, y_pred)
    corr = corr_matrix[0, 1]
    return corr ** 2

In [13]:
mse = loss(y_test, y_pred)
print("MSE:", mse)

MSE: 459.5370240526915


In [14]:
accu = r2_score(y_test, y_pred)
print("Accuracy:", accu)

Accuracy: 0.9780020502895262
