In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

## Dataset

In [2]:
X, y = datasets.make_regression(n_samples=100, n_features=1, noise=20, random_state=10)

In [3]:
X.shape, y.shape

((100, 1), (100,))

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [5]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((80, 1), (20, 1), (80,), (20,))

In [6]:
X_train[:5]

array([[ 2.46765106],
       [ 0.44513761],
       [ 0.39334122],
       [ 0.22863013],
       [-0.96506567]])

In [7]:
y_train[:5]

array([100.37625239,  18.06414221,   8.13026063, -23.57009345,
       -18.86542549])

## Model building

In [8]:
class LinearRegression:
    def __init__(self, learn_rate, num_iters):
        self.weights = None
        self.bias = None
        self.learn_rate = learn_rate
        self.num_iters = num_iters
    
    def fit(self, X, y):                                          # for training the model
        samples, features = X.shape
        self.weights = np.zeros(features)                         # initialising weights as 0 for all features
        self.bias = 0                                             # initialising with bias as 0

        for epoch in range(self.num_iters):
            y_pred = np.dot(X, self.weights) + self.bias          # ypred = b + wX
            loss = ((y_pred-y)**2).mean()                         # MSE: Loss = 1/N * ((w*X+b) - y)**2
            dw = (1 / samples) * 2 * np.dot(X.T, (y_pred - y))    # dLoss/dw = 1/N * 2X(w*X+b - y)
            db = (1 / samples) * 2 * np.sum(y_pred - y)           # dLoss/db = 1/N * 2(w*X+b - y)
            self.weights = self.weights - (self.learn_rate*dw)    # update weight
            self.bias = self.bias - (self.learn_rate*db)          # update bias

            if (epoch%30==0):                                     # just to print loss and weights after some epochs
              print(f'epoch {epoch+1}: weight = {self.weights[0]:.5f}, loss = {loss:.5f}')

    def predict(self, X):                                         # for prediction
        y_pred = np.dot(X, self.weights) + self.bias
        return y_pred

**Logic behind dot products**

np.dot(X, self.weights) --> (80,1) * (1,) = (80,)

for every sample we get 1 value (the 1 is because we have 1 feature)

and in the transposed case,

np.dot(X.T, (y_predicted - y)) --> (1, 80) * (80,) = (1,)

for every feature we get one value

In [9]:
model = LinearRegression(learn_rate=0.01, num_iters=300)
model.fit(X_train, y_train)                                       # used to train model and update w, b
y_pred = model.predict(X_test)

epoch 1: weight = 0.60030, loss = 1287.73851
epoch 31: weight = 14.05484, loss = 646.37925
epoch 61: weight = 21.49845, loss = 450.51270
epoch 91: weight = 25.61988, loss = 390.50173
epoch 121: weight = 27.90367, loss = 372.05698
epoch 151: weight = 29.17016, loss = 366.37054
epoch 181: weight = 29.87303, loss = 364.61229
epoch 211: weight = 30.26341, loss = 364.06711
epoch 241: weight = 30.48038, loss = 363.89763
epoch 271: weight = 30.60107, loss = 363.84480


In [10]:
y_pred[:5]

array([ 34.94644774, -20.91275509,  -2.95632455, -21.96030903,
        19.51838322])

In [11]:
y_test[:5]

array([ 39.61740454, -25.09278505,  -9.7545266 , -14.21925208,
        38.33108551])

## Evaluating test data

In [12]:
def loss(Yhat, Y):
  return ((y_pred-y_test)**2).mean()

def r2_score(y_test, y_pred):
    corr_matrix = np.corrcoef(y_test, y_pred)
    corr = corr_matrix[0, 1]
    return corr ** 2

In [13]:
mse = loss(y_test, y_pred)
print("MSE:", mse)

MSE: 270.9181916072149


In [14]:
accu = r2_score(y_test, y_pred)
print("Accuracy:", accu)

Accuracy: 0.7747921568080172
